default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10

development:
  <<:       *default
  username: nAzgalor
  password: 
  database: ei_development
  host: localhost
  port: 5432

production:
  <<: *default
  username: nAzgalor
  password: 
  database: ei_development
  host: localhost
  port: 5432